2020-09-24 09:59:24 [13372 MainThread:10756] ERROR <module> log.py-18 :"zz" @TAKIN
'[ERROR][zz]'
Traceback (most recent call last):
  File "D:\ÀΩ»À\takin\model\modules\mains\log.py", line 16, in <module>
    print(to445m)
NameError: name 'to445m' is not defined
2020-09-24 10:00:42 [13580 MainThread:12540] ERROR <module> log.py-18 :"zz" @TAKIN
'[ERROR][zz]'
Traceback (most recent call last):
  File "D:\ÀΩ»À\takin\model\modules\mains\log.py", line 16, in <module>
    print(to445m)
NameError: name 'to445m' is not defined
2020-09-24 10:00:54 [4996 MainThread:2656] ERROR <module> log.py-18 :"zz" @TAKIN
'[ERROR][zz]'
Traceback (most recent call last):
  File "D:\ÀΩ»À\takin\model\modules\mains\log.py", line 16, in <module>
    print(to445m)
NameError: name 'to445m' is not defined
